apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vcenter-connector
  namespace: openfaas
  labels:
    app: vcenter
    component: vcenter-connector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vcenter
        component: vcenter-connector
    spec:
      containers:
      - name: vcenter
        image: openfaas/vcenter-connector:0.2.2-rc2
        command: ["./connector"]
        args: ["-vcenter", "http://vcsim.openfaas:8989", "-vc-user-secret-name", "vcenter-username", "-vc-pass-secret-name", "vcenter-password", "-insecure", "-gateway", "http://gateway.openfaas:8080"]
        # To remove auth, remove the volumes and mounts.
        env:
          - name: basic_auth
            value: "true"
          - name: secret_mount_path
            value: "/var/openfaas/secrets/"
        volumeMounts:
            - name: auth-secrets-projected
              readOnly: true
              mountPath: "/var/openfaas/secrets/"
      volumes:
      - name: auth-secrets-projected
        projected:
            defaultMode: 420
            sources:
            - secret:
                items:
                  - key: basic-auth-user
                    path: basic-auth-user
                  - key: basic-auth-password
                    path: basic-auth-password
                name: basic-auth
            - secret:
                items:
                  - key: vcenter-username
                    path: vcenter-username
                  - key: vcenter-password
                    path: vcenter-password
                name: vcenter-secrets
